name: run go-linter-runner
run-name: "run for ${{ inputs.repo_url }}"

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "the repo to run"
        default: "https://github.com/alingse/makezero"
        required: true

permissions:
  issues: write

jobs:
  go-linter-runner-for-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run go-linter-runner with yaml job config
        uses: rusttech/go-linter-runner@v1.0.1
        with:
          action: run
          yaml_config: .github/jobs/alingse-makezero.yaml
          repo_url: ${{ inputs.repo_url }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run go-linter-runner use action config
        uses: rusttech/go-linter-runner@main
        with:
          action: run
          install_command: go install github.com/go-critic/go-critic/cmd/gocritic@latest
          linter_command: gocritic check
          includes: '["go", "github"]'
          excludes: '["assigned by index", "funcall", "called by funcs"]'
          issue_id: 1
          repo_url: ${{ inputs.repo_url }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
